% combine all nima

dataNames = ["run40_2_8deg_DPPC_2px"...
             "run43_multipleredchk_DPPC_2_8deg"...
             "run46_DPPC_300ugmL_1_5deg"...
             "run47_DPPC_300ugmL_1deg"...
             "run48_DPPC_300ugmL_2deg"...
             "run49_DPPC_300ugmL_2_5deg"...
             "run54_DPPC_500ugmL_2deg"...
             "run55_DPPC_500ugmL_2deg_defoc"...
             ];

concs = ["1mg/mL"...
         "1mg/mL"...
         "0.3mg/mL"...
         "0.3mg/mL"...
         "0.3mg/mL"...
         "0.3mg/mL"...
         "0.5mg/mL"...
         "0.5mg/mL"...
         ];

styles = ["-"...
          "-"...
          "-."...
          "-."...
          "-."...
          "-."...
          "--"...
          "--"...
          ];

fileExt = ".fig";
folder = "C:\Users\Christopher\Documents\NatSci\Year 4\Project\MATLAB\CapturedImages\";


fig = figure();
ax = gca;
hold on

for i = 1:length(dataNames)
    fileName = strcat(folder,dataNames(i),"\combine plots\SPvsArea_combined",fileExt);
    dataName = convertStringsToChars(dataNames(i));
    legendName = strcat(dataName(1:5)," ",concs(i));
    f = openfig(fileName);
    l=findobj(f,'type','Line');

    plot(ax,l.XData,l.YData - min(l.YData),'DisplayName',legendName,'LineStyle',styles(i));

    close(f);
end

hold off

legend('location','northeast')

title("all homemade trough runs","Y axes shifted so minimum datapoint is at zero surface pressure")
xlabel("Area per Lipid / angstrom^2");
ylabel("Surface Pressure / mN/m")

savefig(strcat(folder,"DPPC_yOffset 40 to 55.fig"));