% combine all nima

dataNames = ["run1"...
             "run2"...
             "run3"...
             "run4"...
             "run5"...
             "run6"...
             "run8"...
             "run9"...
             ];

concs = ["1mg/mL"...
         "1mg/mL"...
         "1mg/mL"...
         "1mg/mL"...
         "0.3mg/mL"...
         "0.3mg/mL"...
         "0.5mg/mL"...
         "0.5mg/mL"...
         ];

styles = ["-"...
          "-"...
          "-"...
          "-"...
          "-."...
          "-."...
          "--"...
          "--"...
          ];

fileExt = ".xlsx";
folder = "C:\Users\Christopher\Documents\NatSci\Year 4\Project\MATLAB\NIMA data\"


fig = figure();
ax = gca;
hold on
for i = 1:length(dataNames)
    fileName = strcat(folder,dataNames(i),fileExt);
    legendName = strcat(dataNames(i)," ",concs(i));
    A = readmatrix(fileName);
    plot(A(:,1),A(:,2),'DisplayName',legendName,'LineStyle',styles(i));
end

hold off

legend('location','northeast')

title("all NIMA runs")
xlabel("Area per Lipid / angstrom^2");
ylabel("Surface Pressure / mN/m")

savefig(strcat(folder,"NIMA 1 to 9 SPvsArea.fig"));